### ISSUE TITLE
Uncaught Error: No elm-oracle suggestions

### ISSUE THREAD

**Issue by simonh1000** [edubkendo/atom-elm#10] opened 2015-09-16 15:52 UTC
I've added 
`/Users/simon/.nvm/versions/node/v0.12.7/bin/elm-oracle`
as the correct path per the instructions

[Enter steps to reproduce below:]

1. type anything
2. get a stream of error messages - this did not happen on 0.62

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package, v1.0.0

### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /Users/simon/.atom/packages/language-elm/lib/provider.js:72

Error: No elm-oracle suggestions
  at noOutputFromOracleError (/Users/simon/.atom/packages/language-elm/lib/provider.js:62:16)
  at parseOutput (/Users/simon/.atom/packages/language-elm/lib/provider.js:77:17)
  at provideSuggestions (/Users/simon/.atom/packages/language-elm/lib/provider.js:88:67)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -4:56.8.0 core:copy (atom-text-editor.editor.is-focused)
     -4:53.9.0 core:paste (atom-text-editor.editor.is-focused)
     -4:33.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:18.2.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:19.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter-eslint",
      "haskell-ghc-mod",
      "autocomplete-haskell"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
angularjs, v0.3.0
atom-snippets, v0.1.1
atom-typescript, v6.0.8
autocomplete-sass, v0.1.0
color-picker, v2.0.11
ide-haskell, v0.7.2
language-elm, v1.0.0
language-haskell, v1.4.4
language-jade, v0.6.2
linter, v1.5.1
pretty-json, v0.4.1
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by edubkendo** [comment] 2015-09-16 18:43
@brianegan

**Comment by sanichi** [comment] 2015-09-17 06:44
I have the same problem except my elm-oracle path is `/usr/local/bin/elm-oracle`.

It seems that the problem is caused by the variable `executablePath` in `.atom/packages/language-elm/lib/provider.js` being undefined. So a temporary fix for me was to replace line 16:

    const executablePath = atom.config.get('atom-elm-autocomplete.elmOraclePath');

with:

    const executablePath = "/usr/local/bin/elm-oracle";

**Comment by simonh1000** [comment] 2015-09-17 06:57
Cool - that works for me too (with appropriate path change)

**Comment by sanichi** [comment] 2015-09-18 07:39
It appears that atom's configuration settings are saved to the file `.atom/config.cson` and, having taken a peek at that file, the name used for the elm-oracle path in `provider.js` doesn't look right. So now this works for me:

    const executablePath = atom.config.get('language-elm.elmOraclePath');

**Comment by brianegan** [comment] 2015-09-18 10:03
Thanks for the bug reports! And sorry all. Thanks @sanichi for spotting the issue.

I originally developed this feature under a package called `atom-elm-autocomplete` and then decided to merge it with this `language-elm` package. However, I left that old reference in place.

I've updated master. @edubkendo, could you please publish the new version? I've bumped the package.json version to `1.0.1`.

**Comment by edubkendo** [comment] 2015-09-18 12:03
Published. For future reference, apm automatically bumps the package.json so no need to do that part :)

**Comment by brianegan** [comment] 2015-09-18 20:45
Cool, thanks for the heads up :)

**Comment by jice** [comment] 2015-09-18 22:41
Still getting those errors in 1.0.2 on Windows

[Enter steps to reproduce below:]

1. install elm-language
2. follow instructions to install elm-oracle and provide path in settings

**Atom Version**: 1.0.14
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package, v1.0.2


### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /C:/Users/user/.atom/packages/language-elm/lib/provider.js:77

Error: No elm-oracle suggestions
  at noOutputFromOracleError (C:\Users\user\.atom\packages\language-elm\lib\provider.js:62:16)
  at parseOutput (C:\Users\user\.atom\packages\language-elm\lib\provider.js:77:17)
  at provideSuggestions (C:\Users\user\.atom\packages\language-elm\lib\provider.js:88:67)
  at triggerExitCallback (C:\Users\user\AppData\Local\atom\app-1.0.14\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.0.14\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
  2x -1:22.2.0 core:paste (atom-text-editor#language-elm.elmOraclePath.editor.mini.is-focused)
     -0:12.1.0 core:backspace (atom-text-editor#language-elm.elmOraclePath.editor.mini.is-focused)
  3x -0:11.8.0 core:confirm (atom-text-editor#language-elm.elmOraclePath.editor.mini.is-focused)
  4x -0:06.7.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "language-elm": {
    "elmOraclePath": "C:\\Users\\user\\AppData\\Roaming\\npm\\elm-oracle"
  }
}
```

### Installed Packages

```coffee
# User
language-elm, v1.0.2
language-glsl, v2.0.1

# Dev
No dev packages
```

**Comment by lehoff** [comment] 2015-09-21 09:48
I'm having the same issue.

It complains about elm-oracle's path and wants me to run "elm package install" in my project folder - which I have done.

Running:
language-elm 1.0.2
On a Mac OS X 10.10.5

**Comment by digiduke** [comment] 2015-09-22 16:55
Like the two above, I'm also still experiencing this, despite having the correct elm-oracle path. I have language-elm 1.02 and Mac OS X 10.10.5 (pretty bare Atom install...no other user packages).

**Comment by edubkendo** [comment] 2015-09-22 18:54
@brianegan looks like some folks are still having troubles

**Comment by ivanoats** [comment] 2015-09-24 23:29
Maybe it has something to do with Elm source files being put in sub directories?  look in lines 13-22 of provider.js.

 For example, I have my elm code in a src directory off of my project root.

**Comment by iamwilhelm** [comment] 2015-09-25 18:09
@ivanoats I noticed that for me as well. It looks like Elm source files don't work if they're in subdirectories. It looks like line#13 just normalizes the path. Why would that make it not work?

**Comment by ivanoats** [comment] 2015-09-25 18:21
Line 13 currently takes the path of the current file being edited, but doesn't point to the project root (where elm-package.json is), which is different. In order to get elm-oracle working for me, I had to replace it with the project directory, as in my #11 P.R.

**Comment by iamwilhelm** [comment] 2015-09-25 19:36
Thanks that solved my problem for now. I hope there'll be an update soon.

**Comment by edubkendo** [comment] 2015-09-25 19:38
Just waiting to see if any discussion happens in his PR, or if anyone proposes something more general

**Comment by digiduke** [comment] 2015-09-26 00:47
I am seeing mixed results depending on which project files I am editing and noted the following. 

It looks like elm-oracle will error out and trigger the messages in this issue if it can't open `elm-stuff/exact-dependencies.json`. So it expects the current path to be the same place you would run `elm package install` (and that you have done so). This can be seen by invoking elm-oracle manually the same way autocomplete would from a path where that isn't the case, resulting in some output to stderr like:

```
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'elm-stuff/exact-dependencies.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at readFile (/usr/local/lib/node_modules/elm-oracle/bin/elm-oracle:7044:13)
    at main [as _onTimeout] (/usr/local/lib/node_modules/elm-oracle/bin/elm-oracle:7026:28)
    at Timer.listOnTimeout (timers.js:89:15)
```

Perhaps a stderr result like this could be captured and included in the messaging by atom-elm, and/or perhaps it should be suggested that elm-oracle guard against this and default to no dependencies (say you're scratching around in a new elm file without a project context), or return an error in JSON as it looks like it does with other things.

**Comment by brianegan** [comment] 2015-09-27 17:45
Thanks all! Sorry, been in and out the past couple weeks. Taking a look tonight and I'll code up a solution :)

Best,
Brian

**Comment by brianegan** [comment] 2015-09-27 23:07
Just put up a pull request with a fix to this issue! Could a couple of you give it a shot and let us know if it resolves the problem? Thanks!

**Comment by edubkendo** [comment] 2015-09-28 00:31
Whoops! sorry @brianegan , I saw your PR and went ahead and published. Should have read all my email first lol.

**Comment by brianegan** [comment] 2015-09-28 08:21
Haha, no worries at all :) I tested it in quite a few scenarios, so hopefully it'll work the first time!

**Comment by kevinrood** [comment] 2015-09-30 14:26
I'm still experiencing this on Windows.

[Enter steps to reproduce below:]

1. install elm-language
1. follow instructions to install elm-oracle and provide path in settings
1. type in elm source file

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Pro
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package, v1.0.3


### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /C:/Users/Kevin/.atom/packages/language-elm/lib/provider.js:129

Error: No elm-oracle suggestions
  at noOutputFromOracleError (C:\Users\Kevin\.atom\packages\language-elm\lib\provider.js:108:16)
  at parseOutput (C:\Users\Kevin\.atom\packages\language-elm\lib\provider.js:129:17)
  at provideSuggestions (C:\Users\Kevin\.atom\packages\language-elm\lib\provider.js:140:67)
  at triggerExitCallback (C:\Users\Kevin\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Kevin\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -2:27.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:25.8.0 core:paste (atom-text-editor.editor.is-focused)
  2x -2:25.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:24.8.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -2:24.2.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:23.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:23.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:23 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:23 snippets:expand (atom-text-editor.editor.is-focused)
     -2:23 editor:indent (atom-text-editor.editor.is-focused)
     -0:19.3.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:08.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:07.6.0 core:delete (atom-text-editor.editor.is-focused)
     -0:07.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:03.4.0 core:delete (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "language-csharp"
    ]
  },
  "language-elm": {
    "elmOraclePath": "C:\\Users\\Kevin\\AppData\\Roaming\\npm\\elm-oracle"
  }
}
```

### Installed Packages

```coffee
# User
language-elm, v1.0.3

# Dev
No dev packages
```

**Comment by inouiw** [comment] 2015-09-30 20:06
I can confirm that it throws noOutputFromOracleError on Windows, even though executing the command line "C:\Users\David\AppData\Roaming\npm\elm-oracle.cmd C:\Users\David\Documents\elm-test1\main.elm l" in the console does work.

**Comment by kunjee17** [comment] 2015-10-01 19:00
I tried above solutions but still facing the issue. Using version 1.0.3. Is patch updated?

**Comment by NicholasGW** [comment] 2015-10-03 19:56
Dug into this a little today, it appears that the BufferedNodeProcess being spawned returns an exit value of 1 (Fatal error) but for some reason it's not being caught or handled, even if I fill out stderr etc.  
 
Not sure of the cause but it could be a problem with the Atom class itself as I saw a few errors. Doing some inspection yields that all the params for elm-oracle (path, filename, prefix) are correct on my system and if I run the command as seen in my own shell, it executes correctly, so the problem is with the spawned child process, not the args.

**Comment by NicholasGW** [comment] 2015-10-03 20:58
Didn't want to upload a PR because I'm new to node development, I but I think I confirmed that BufferedNodeProcess is screwing up the command...looks like there's some weird double quotes going on.  
  
If you replace lines 131 on in provider.js with the following, it seems to work on Windows. the line with 'cmd.exe' etc would obviously break on non-windows, but it shows that elm-oracle etc can be run correctly.  
  
      const filePath = editor.getPath();
      const elmProjectPath = findClosestElmProjectPath(filePath.split(sep).slice(0, -1));
      const executablePath = atom.config.get('language-elm.elmOraclePath');
      const options = {
        cwd: elmProjectPath,
        env: process.env,
        error: myError,
        stdout: accumulateOutput,
        stderr: myError,
        exit: provideSuggestions
      };

      var results = child_process.spawn(
        'cmd.exe',
        ['/c', executablePath, filePath, prefix],
         options);

        results.stdout.on('data', function(data) {
        accumulateOutput(data.toString());
        });

        results.on('close', function(status) {
          provideSuggestions(status);
        });

**Comment by kevinrood** [comment] 2015-10-04 02:45
Do you want to try your hand at a PR that simply branches based on platform?

stackoverflow.com/questions/8683895/how-do-i-determine-the-current-operating-system-with-node-js

**Comment by NicholasGW** [comment] 2015-10-05 12:20
I can perhaps try a PR this week, pretty busy. However, it seems like this issue has been spotted elsewhere awhile ago...asked for an update.
  
https://github.com/atom/atom/issues/2887

**Comment by kunjee17** [comment] 2015-10-06 09:29
@NicholasGW it is kind of stopping me from using Atom with elm. And I guess right now Atom is only editor which is having auto complete feature for elm. It is kinda easy to learn new language if I have autocomplete. 

@brianegan please have a look or put a gist or something like that to have work around.

**Comment by lepinay** [comment] 2015-10-06 10:09
That would be great to have that one fixed on windows.
@brianegan Could we have at least the ability to disable auto completion as an option ? That way windows users could have syntax highlight while this is being fixed. At the moment, each keystroke triggers a dozen of error popups.

**Comment by NicholasGW** [comment] 2015-10-06 12:20
@kunjee17  I think the ability to disable autocomplete is available in 1.10, so that's a temporary way to get at least syntax highlighting.  
  
I have submitted a PR with *my* windows fix that should hopefully work. It might require having node available on the command line path, but that's pretty standard for most people I think. We'll see what @edubkendo and @brianegan think of my shoddy code ;).

**Comment by brianegan** [comment] 2015-10-07 12:19
Hey all, thanks for writing in and sorry about the trouble on windows! It's a difficult environment for me to test on, and I appreciate your patience :)

@NicholasGW thanks so much for finding the root cause and submitting a PR that fixes your issue! I've merged that PR into the master branch. @edubkendo, when you get a chance, could you please publish a new version to see if it helps our friends coding Elm on Windows?

If you still run into problems, please stop submit more bug reports. One thing that can help: I'm now reporting the full stack trace if an error occurs when running the elm-oracle process when you're in Dev Mode. To enable dev mode, simply go to: View -> Developer -> Open in Dev mode.

**Comment by edubkendo** [comment] 2015-10-07 12:21
already done ;)

**Comment by brianegan** [comment] 2015-10-07 12:21
@edubkendo Dayang that was fast ;)

**Comment by lepinay** [comment] 2015-10-07 14:09
Thanks for fixing that one, just tested 1.1.1 on windows and it works great.
Only thing is that auto complete only work for Elm libraries not for user defined types, not sure if that was already implemented. But having autocomplete working on Elm libs is already a huge time saver :)

**Comment by NicholasGW** [comment] 2015-10-07 14:12
@lepinay Good to hear! I imagine for user-defined types that would have to be added to elm-oracle...I think right now it just queries the available documentation and returns what's in there.

**Comment by kunjee17** [comment] 2015-10-09 10:12
I ll check today and post reply. Thanks for faster update. :)

**Comment by kunjee17** [comment] 2015-10-09 16:52
It worked. It worked. It worked. :+1: Thanks.

**Comment by brianegan** [comment] 2015-10-12 15:20
Thanks for the comments, PRs and help y'all! Gonna go ahead and (optimistically) close this one out for now :)

**Closed by brianegan** 2015-10-12 15:20 UTC

**Comment by VitorCBSB** [comment] 2016-01-06 22:28
So, uh, I'm hitting this error at the moment. If I had to guess, it's probably because one of my directories, "Vitor Coimbra", having a space character (a trait that has caught oh so many bugs on other projects).

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package, v1.3.0


### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /C:/Users/Vitor%20Coimbra/.atom/packages/language-elm/lib/provider.js:278

Error: No elm-oracle suggestions
    at noOutputFromOracleError (C:/Users/Vitor Coimbra/.atom/packages/language-elm/lib/provider.js:227:10)
    at parseOutput (C:/Users/Vitor Coimbra/.atom/packages/language-elm/lib/provider.js:256:11)
    at provideSuggestions (C:/Users/Vitor Coimbra/.atom/packages/language-elm/lib/provider.js:59:15)
    at ChildProcess.<anonymous> (C:/Users/Vitor Coimbra/.atom/packages/language-elm/lib/provider.js:95:11)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -6:39.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:05.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:29.8.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -4:57.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:55.1.0 core:save (atom-text-editor.editor.is-focused)
     -4:52.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "language-elm": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.2
haskell-ghc-mod, v1.5.3
ide-haskell, v1.3.9
ide-haskell-cabal, v1.0.0
language-elm, v1.3.0
language-haskell, v1.5.2

# Dev
No dev packages
```

**Comment by NicholasGW** [comment] 2016-01-07 15:27
This is indeed still an issue with spaces in the name! Due to the result of spawning the process.

A workaround, if possible, is to install elm-oracle globally and just don't input a path at all in the settings for language-elm. That way, it will just execute it from the command line as elm-oracle which works for me. Not sure what this will do for linux/Mac users.

Will look into a fix.

**Comment by VitorCBSB** [comment] 2016-01-08 14:03
Ah yes, setting the problematic directory to its short name (VITORC~1) works for me, autocomplete works as expected now. Thanks for the help. :+1:

**Comment by NicholasGW** [comment] 2016-01-08 14:05
Awesome! Definitely should work with long path names but that's an easy enough workaround for now :). Cheers

**Comment by avatar29A** [comment] 2016-02-25 11:00
I got same error. What can I do? Thnks

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Unknown Windows Version
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package, v1.3.2


### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /C:/Users/bglebov/.atom/packages/language-elm/lib/elmOracle.js:144

Error: No elm-oracle suggestions
    at parseOutput (C:/Users/bglebov/.atom/packages/language-elm/lib/elmOracle.js:125:11)
    at provideSuggestions (C:/Users/bglebov/.atom/packages/language-elm/lib/elmOracle.js:27:27)
    at ChildProcess.<anonymous> (C:/Users/bglebov/.atom/packages/language-elm/lib/elmOracle.js:62:9)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "language-elm": {
    "elmOraclePath": "C:\\Users\\bglebov\\AppData\\Roaming\\npm\\node_modules\\elm-oracle\\bin\\elm-oracle"
  }
}
```

### Installed Packages

```coffee
# User
atom-python-debugger, v0.3.4
autocomplete-python, v1.6.1
haskell-pointfree, v0.1.3
ide-haskell-cabal, v1.0.0
language-elm, v1.3.2
language-elmx, v1.2.0
language-haskell, v1.5.2
language-lisp, v0.1.2
linter, v1.11.3
linter-elm-make, v0.4.0
python-indent, v0.3.3
python-iresolve, v0.0.3
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by avatar29A** [comment] 2016-02-25 11:34
I fixed it. Just I set elmOraclePath as elm-oracle.

**Comment by hipertracker** [comment] 2016-03-01 12:10
**There is something broken in Windows 7**. Elm auto completion works for me on Windows 10 and OS X 10.11.4 Beta (except Atom very often freezes on OS X). 

In all cases I have just fresh Atom v1.5.3 and language-elm v1.3.3  (+ core packages).

**Comment by vilinski** [comment] 2016-03-07 11:04
@avatar29A Tnank you works for me too!
* install with `npm install -g elm-oracle` 
* just set `elm-oracle` instead of full path to it

**Comment by hipertracker** [comment] 2016-04-15 10:24
Problem is gone with the right path. It should **not **be path to _elm-oracle_, but to the folder whet it is located! In my case C:\Users\hipertracker\.atom\packages\language-elm\node_modules\elm-oracle\bin

**Comment by mm-tfx** [comment] 2016-10-10 11:35
I must be missing something because this is not working for me still.
I have tried several different paths to elm-oracle but neither works.

I keep geting this fault in Atom:
Error: No elm-oracle suggestions
    at parseOutput (C:/Users/qmarmik/.atom/packages/language-elm/lib/elmOracle.js:125:11)
    at provideSuggestions (C:/Users/qmarmik/.atom/packages/language-elm/lib/elmOracle.js:27:27)
    at ChildProcess.<anonymous> (C:/Users/qmarmik/.atom/packages/language-elm/lib/elmOracle.js:62:9)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
